language: python
python:
 - "2.7"

script: echo "DONE"

install:
 - sudo apt-get install python-numpy python-scipy python-matplotlib
 - pip install --no-deps astropy
 - pip install --no-deps emcee
 - pip install --no-deps lenstools 

virtualenv:
 system_site_packages: true
