language: python
python:
 - 2.7
 - 3.4

notifications:
email: false  

#####################################################
#From: https://gist.github.com/dan-blanchard/7045057#
#####################################################

#Setup anaconda
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda2/bin:$PATH
- conda update --yes conda

#GSL
- mkdir cextern
- "export LD_LIBRARY_PATH=/home/travis/build/apetri/LensTools/cextern/lib:$LD_LIBRARY_PATH" 
- wget http://ftpmirror.gnu.org/gsl/gsl-1.16.tar.gz
- tar -xvf gsl-1.16.tar.gz
- cd gsl-1.16
- ./configure --prefix=/home/travis/build/apetri/LensTools/cextern
- make
- make install
- cd ..

#The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm

#Install packages
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION atlas 
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy 
- conda install --yes python=$TRAVIS_PYTHON_VERSION scipy 
- conda install --yes python=$TRAVIS_PYTHON_VERSION sqlalchemy 
- conda install --yes python=$TRAVIS_PYTHON_VERSION matplotlib 
- conda install --yes python=$TRAVIS_PYTHON_VERSION nose 
- conda install --yes python=$TRAVIS_PYTHON_VERSION pandas 
- conda install --yes python=$TRAVIS_PYTHON_VERSION numexpr 
- conda install --yes python=$TRAVIS_PYTHON_VERSION astropy

#Coverage packages
- pip install coveralls
- python setup.py build_ext -i --gsl=/home/travis/build/apetri/LensTools/cextern
- python setup.py install --gsl=/home/travis/build/apetri/LensTools/cextern

#Set up display
before_script: 
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

#Run test
script:
- nosetests --with-coverage --cover-package=lenstools --logging-level=INFO

# Calculate coverage
after_success:
- coveralls
