language: python
python:
 - "2.7"

script: echo "DONE"

install:
 - git clone https://github.com/apetri/LensTools
 - cd LensTools
 - python setup.py install
 - cd ..
 - rm -rf LensTools
 - sudo apt-get install python-numpy python-scipy
 - pip install emcee
 - pip install --no-deps astropy 

virtualenv:
 system_site_packages: true
