language: python
python:
 - "2.7"

script: 

install:
 - git clone https://github.com/apetri/LensTools
 - cd LensTools
 - python setup.py install
 - cd ..
 - rm -rf LensTools

virtualenv:
 system_site_packages: true
